base_link:
  sensor_kit_base_link:
    x: 0.0 #0.9
    y: 0.0
    z: 1.6 #2.0
    roll: 0.0 #-0.001
    pitch: 0.0 #0.015
    yaw: 0.0 #-1.57 #0.0 #-0.0364
  velodyne_rear_base_link:
    x: 0.0 #-0.358
    y: 0.0
    z: 0.0 #1.631
    roll: 0.0 #-0.02
    pitch: 0.0 #0.7281317
    yaw: 0.0 #3.141592
